package com.ritmute.core.domain.model

/**
 * Local row identifier. Auto-generated by the database, never leaves the app and
 * never participates in any user-observable ordering.
 *
 * Business identity is carried by [SoundProfile.uuid] / [Schedule.uuid], which are
 * stable across devices and survive export/import. See docs/02, decision D-C6.
 */
@JvmInline
value class ProfileId(val value: Long) {
    val isPersisted: Boolean get() = value != 0L

    companion object {
        val UNSAVED = ProfileId(0)
    }
}

@JvmInline
value class ScheduleId(val value: Long) {
    val isPersisted: Boolean get() = value != 0L

    companion object {
        val UNSAVED = ScheduleId(0)
    }
}
